In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import statsmodels.api as sm
from scipy.stats import boxcox

pd.options.display.max_rows = 50

In [2]:
NewCA = pd.read_csv('newdataframe')
NewCA

,Unnamed: 0,region_central,region_east,region_north west,region_west region,response_no,response_yes,coverage_basic,coverage_extended,coverage_premium,...,vehicle_size_small,Unnamed: 0.1,customer_lifetime_value,income,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,number_of_open_complaints,number_of_policies,total_claim_amount
0,0,1,0,0,0,1,0,1,0,0,...,0,0,4809,48029,61,7,52,0,9,292
1,1,0,0,0,1,1,0,1,0,0,...,0,1,2228,26794,64,3,26,0,1,744
2,2,0,1,0,0,1,0,1,0,0,...,0,2,14947,22139,100,34,31,0,2,480
3,3,0,0,1,0,0,1,0,1,0,...,0,3,22332,49078,97,10,3,0,2,484
4,4,0,0,1,0,1,0,0,0,1,...,0,4,9025,23675,117,15,31,1,7,707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10684,10684,1,0,0,0,1,0,0,0,1,...,0,10684,15563,64811,253,8,40,2,7,1214
10685,10685,0,0,1,0,1,0,1,0,0,...,0,10685,5259,61146,65,7,68,0,6,273
10686,10686,1,0,0,0,1,0,0,1,0,...,0,10686,23893,39837,201,11,63,0,2,381
10687,10687,0,0,0,1,1,0,0,0,1,...,0,10687,11971,64195,158,0,27,4,6,618
10688,10688,0,0,0,1,1,0,1,0,0,...,0,10688,6857,88784,101,31,1,0,3,1021

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [26]:
NewCA=NewCA.drop('Unnamed: 0', axis=1)

In [25]:
X=X.drop('Unnamed: 0', axis=1)

KeyError: "['Unnamed: 0'] not found in axis"

In [15]:
X=NewCA.drop('total_claim_amount', axis=1)

In [17]:
y=NewCA.total_claim_amount

In [18]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=.30,random_state=123)

In [19]:
std_scaler=StandardScaler().fit(X_train)

In [20]:
X_train_scaled=std_scaler.transform(X_train)

In [21]:
X_train.shape

(7482, 57)